### ISSUE TITLE
Mode collapse with a large dataset

### ISSUE THREAD

**Issue by Poofy1** [NVlabs/stylegan2-ada-pytorch#104]
First off I would just like to say this most likely is not a bug. I am mostly just asking for advice because I'm not very familiar with the program's config and this page didn't explain the settings in much depth.

I have a dataset of about 65000 images and I expected the snapshot images to be very diverse but they are all very similar. This started becoming noticeable around the 200kimg mark. I believe this is mode collapse. I am using the default settings currently. I have not really tried anything because I don't know what to change. Perhaps increasing batch_size or ada_kimg will help prevent it? 

My main questions:
Is there a config setting that I can change that will help prevent mode collapse from happening? Do you have any other advice to prevent mode collapse?

![fakes000240](https://user-images.githubusercontent.com/70146048/117386588-cbb24d00-aeac-11eb-80fe-908811b7dedf.png)

**Desktop:**
 - OS: Windows 10
 - PyTorch version 1.7.1
 - CUDA toolkit version CUDA 11.1
 - NVIDIA driver version: 466.11
 - RTX 3070 
 - Anaconda enviroment

**Comment by abstractdonut** [comment]
Have you continued training your model since posting this? If so, do recent snapshots show more diversity?

Does your dataset have a lot of variation? Are all images cropped and centered and do they contain a single class of object from a single point of view, or are there multiple types of objects depicted?

**Comment by Poofy1** [comment]
As I trained more it became more diverse, so it has seemed to fix itself. Thanks :)

**Comment by katie-cathy-hunt** [comment]
@Poofy1 Hi! After how many kimgs did the snapshot become more diverse?
