### ISSUE TITLE
stucks on Setting up PyTorch plugin "upfirdn2d_plugin"...

### ISSUE THREAD

**Issue by ronghui19** [NVlabs/stylegan2-ada-pytorch#11]

**Comment by nurpax** [comment]
When filing bugs, please be more specific about what you have been trying to run, on what platform, and on what GPU.  Even if the details feel irrelevant or trivial to you, they're often key to figuring out what might be wrong.  

One known problem with PyTorch extension builds is that breaking the build may sometimes leave a lock file under `$HOME/.cache/torch_extensions` (Linux).  You can try to delete this whole directory and try again.

Please refer to PyTorch documentation to find out where the torch_extensions directory resides if you can't find it.  I'm not where it gets put on Windows.

If the above doesn't fix your problem, feel free to file a new bug.  But please be more specific about what your environment, what commands you tried, software versions.

**Comment by woctezuma** [comment]
Most likely: https://github.com/NVlabs/stylegan2-ada-pytorch/issues/2

**Comment by ronghui19** [comment]
> When filing bugs, please be more specific about what you have been trying to run, on what platform, and on what GPU. Even if the details feel irrelevant or trivial to you, they're often key to figuring out what might be wrong.
> 
> One known problem with PyTorch extension builds is that breaking the build may sometimes leave a lock file under `$HOME/.cache/torch_extensions` (Linux). You can try to delete this whole directory and try again.
> 
> Please refer to PyTorch documentation to find out where the torch_extensions directory resides if you can't find it. I'm not sure where it gets put on Windows.
> 
> If the above doesn't fix your problem, feel free to file a new bug. But please be more specific about what your environment, what commands you tried, software versions.

it works

**Comment by Anis-bourou** [comment]
It works, thank you very much!

**Comment by koyuyesil** [comment]
C:\Users\user\AppData\Local\torch_extensions

**Comment by gonduras** [comment]
@koyuyesil thanks!
