### ISSUE TITLE
Stuck on Evaluating Metrics

### ISSUE THREAD

**Issue by Adblu** [NVlabs/stylegan2-ada-pytorch#120]
After downloading afhq dataset and after creating zip file with:
```
python dataset_tool.py --source=downloads/afhq/afhq/train/cat --dest=datasets/cat.zip
```
I start the train:
```
python train.py --outdir=training-runs --data=datasets/cat.zip --gpus=1
```
and execution stops at Evaluate metrics:
```
Discriminator  Parameters  Buffers  Output shape        Datatype
---            ---         ---      ---                 ---     
b512.fromrgb   256         16       [8, 64, 512, 512]   float16 
b512.skip      8192        16       [8, 128, 256, 256]  float16 
b512.conv0     36928       16       [8, 64, 512, 512]   float16 
b512.conv1     73856       16       [8, 128, 256, 256]  float16 
b512           -           16       [8, 128, 256, 256]  float16 
b256.skip      32768       16       [8, 256, 128, 128]  float16 
b256.conv0     147584      16       [8, 128, 256, 256]  float16 
b256.conv1     295168      16       [8, 256, 128, 128]  float16 
b256           -           16       [8, 256, 128, 128]  float16 
b128.skip      131072      16       [8, 512, 64, 64]    float16 
b128.conv0     590080      16       [8, 256, 128, 128]  float16 
b128.conv1     1180160     16       [8, 512, 64, 64]    float16 
b128           -           16       [8, 512, 64, 64]    float16 
b64.skip       262144      16       [8, 512, 32, 32]    float16 
b64.conv0      2359808     16       [8, 512, 64, 64]    float16 
b64.conv1      2359808     16       [8, 512, 32, 32]    float16 
b64            -           16       [8, 512, 32, 32]    float16 
b32.skip       262144      16       [8, 512, 16, 16]    float32 
b32.conv0      2359808     16       [8, 512, 32, 32]    float32 
b32.conv1      2359808     16       [8, 512, 16, 16]    float32 
b32            -           16       [8, 512, 16, 16]    float32 
b16.skip       262144      16       [8, 512, 8, 8]      float32 
b16.conv0      2359808     16       [8, 512, 16, 16]    float32 
b16.conv1      2359808     16       [8, 512, 8, 8]      float32 
b16            -           16       [8, 512, 8, 8]      float32 
b8.skip        262144      16       [8, 512, 4, 4]      float32 
b8.conv0       2359808     16       [8, 512, 8, 8]      float32 
b8.conv1       2359808     16       [8, 512, 4, 4]      float32 
b8             -           16       [8, 512, 4, 4]      float32 
b4.mbstd       -           -        [8, 513, 4, 4]      float32 
b4.conv        2364416     16       [8, 512, 4, 4]      float32 
b4.fc          4194816     -        [8, 512]            float32 
b4.out         513         -        [8, 1]              float32 
---            ---         ---      ---                 ---     
Total          28982849    480      -                   -       

Setting up augmentation...
Distributing across 1 GPUs...
Setting up training phases...
Exporting sample images...
Initializing logs...
Skipping tfevents export: No module named 'tensorboard'
Training for 25000 kimg...

tick 0     kimg 0.0      time 50s          sec/tick 11.2    sec/kimg 1397.00 maintenance 39.2   cpumem 4.61   gpumem 10.32  augment 0.000
Evaluating metrics...
```

 - OS: Ubuntu 18.04
 - PyTorch version 1.8.1
 - CUDA toolkit version 11.1
 - NVIDIA Driver Version: 460.80
 - GPU nvidia T4
 - Docker: did you use Docker?  no

What might be the reason for such behavior ?

**Comment by ridhachahed** [comment]
@Adblu what was your problem ? I have the same !

**Comment by ridhachahed** [comment]
After debugging it was a memory problem and reducing the number of workers fixed it :)

**Comment by Vova-B** [comment]
@ridhachahed Hi! Are you just reduced the size of the workers or made some other changes? I have the same problem :(

**Comment by Mo-Irene** [comment]
@Vova-B Hi，I also encountered this problem, if you have any progress or find any trouble, please let me know, I will be very grateful for your sharing :)

**Comment by Adblu** [comment]
@Mo-Irene  It turned out that metrics evaluation takes awful lot of time, which leaves an impression  that it stuck. Just wait ;)

**Comment by Mo-Irene** [comment]
> @Mo-Irene It turned out that metrics evaluation takes awful lot of time, which leaves an impression that it stuck. Just wait ;)

Thank you, I also found out about this later :)

**Comment by MationPlays** [comment]
> @Mo-Irene It turned out that metrics evaluation takes awful lot of time, which leaves an impression that it stuck. Just wait ;)

I let it go for a couple hours but still evaluating metrics... how long should it take? I use an google colab free version with it

**Comment by Mo-Irene** [comment]
> > @Mo-Irene It turned out that metrics evaluation takes awful lot of time, which leaves an impression that it stuck. Just wait ;)
> 
> I let it go for a couple hours but still evaluating metrics... how long should it take? I use an google colab free version with it

Actually, I don't quite remember how long it took. I was using Nvidia Titan RTX GPU, maybe for a few hours or so. Just wait:)

**Comment by erjel** [comment]
> I encountered the same problem. For me, it is so slow to download the fid model [fid model url path](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/d4b2afe9c27e3c305b721bc886d2cb5229458eba/metrics/frechet_inception_distance.py#L22)
> 
> So, I down the model Individually. And change load model method. Then, It can work well. PS: It not works in pytorch 1.9. And I downgrad the pytorch version to 1.8.0

A little more explicit for people running this on compute node(s) without internet connection:

1.) Download the detector on a machine with internet connection
```
wget https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/metrics/inception-2015-12-05.pt
```

2.) Move the weights to a folder (here placeholder: `<absolute_path_to_weights_directory>`) which can be accessed by the offline compute node(s)

3.) Change [this line](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/d4b2afe9c27e3c305b721bc886d2cb5229458eba/metrics/frechet_inception_distance.py#L22) to something like:
```
detector_url = 'file://<absolute_path_to_weights_directory>/inception-2015-12-05.pt'
```

**Comment by Arunprakash-1903** [comment]
I used --metrics none for skipping Metrics Evaluation
