### ISSUE TITLE
Why the synthesis network doesn't use the fused_modconv like the stylegan2's did?

### ISSUE THREAD

**Issue by hallwaypzh** [NVlabs/stylegan2-ada-pytorch#122]
It seems that the default behavior for the synthesis layer is: modulate convolution kernel -> demodulate convolution kernel -> modulate input feature map -> apply convolution -> demodulate output feature map; is there any specific reason for this?

**Comment by htzheng** [comment]
Hi @hallwaypzh, did you figure it out? It seems that the fused_modconv operation is not used during training.
