### ISSUE TITLE
UserWarning: semaphore_tracker: There appear to be 34 leaked semaphores to clean up at shutdown 

### ISSUE THREAD

**Issue by wandrzej** [NVlabs/stylegan2-ada-pytorch#131]
I'm getting this error on a Google Colab. This started showing up all of a sudden in the last two days, I've only changed the data,  code remained pretty much the same
```
tick 0     kimg 0.0      time 2m 59s       sec/tick 7.9     sec/kimg 989.17  maintenance 170.8  cpumem 4.98   gpumem 10.59  augment 0.000
Evaluating metrics...
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:1051: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return forward_call(*input, **kwargs)
/usr/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 34 leaked semaphores to clean up at shutdown
  len(cache))
```
Happened on Tesla T4  and P100, restarted the hosted runtime a few times, hew no much difference

**Comment by lukas-hauser** [comment]
I have the same issue and exactly the same warnings - I was able to train on Colab for a while and also resumed multiple times, however since 18th Jun, the warnings appear, and the training won't continue. I did not change the code nor the data.

**Comment by wandrzej** [comment]
I think the only thing that could have changed is something on Google Colab side. I haven't changed the code, tried resuming, training from scratch with different datasets - same situation and it's odd we're getting the exact same error and Colab is the common denominator in both cases.  Odd to say the least

**Comment by sugyan** [comment]
PyTorch 1.9 was released on 15, June. and now it seemed to be used as default in Colab.

https://pytorch.org/blog/pytorch-1.9-released/

I did downgrade to the previous version and succeeded to run training.

`!pip install torch==1.8.1 torchvision==0.9.1`

**Comment by lukas-hauser** [comment]
Great thank you, that worked.

I did actually try downgrading PyTorch 2 days ago, but apparently to the wrong version (1.8.0 / 0.9.0) which didn't work.

**Comment by wandrzej** [comment]
At least now I'm getting a different error 
```
Traceback (most recent call last):
  File "/content/stylegan2-ada-pytorch/train.py", line 538, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/content/stylegan2-ada-pytorch/train.py", line 531, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "/content/stylegan2-ada-pytorch/train.py", line 383, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/content/stylegan2-ada-pytorch/training/training_loop.py", line 375, in training_loop
    dataset_kwargs=training_set_kwargs, num_gpus=num_gpus, rank=rank, device=device)
  File "/content/stylegan2-ada-pytorch/metrics/metric_main.py", line 45, in calc_metric
    results = _metric_dict[metric](opts)
  File "/content/stylegan2-ada-pytorch/metrics/metric_main.py", line 85, in fid50k_full
    fid = frechet_inception_distance.compute_fid(opts, max_real=None, num_gen=50000)
  File "/content/stylegan2-ada-pytorch/metrics/frechet_inception_distance.py", line 27, in compute_fid
    rel_lo=0, rel_hi=0, capture_mean_cov=True, max_items=max_real).get_mean_cov()
  File "/content/stylegan2-ada-pytorch/metrics/metric_utils.py", line 215, in compute_feature_stats_for_dataset
    for images, _labels in torch.utils.data.DataLoader(dataset=dataset, sampler=item_subset, batch_size=batch_size, **data_loader_kwargs):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1179, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/stylegan2-ada-pytorch/training/dataset.py", line 88, in __getitem__
    assert list(image.shape) == self.image_shape
AssertionError
```

**Comment by timendez** [comment]
@wandrzej Did you ever figure out your error? I have the same one 

> 
> 
> At least now I'm getting a different error
> 
> ```
> Traceback (most recent call last):
>   File "/content/stylegan2-ada-pytorch/train.py", line 538, in <module>
>     main() # pylint: disable=no-value-for-parameter
>   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 21, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/content/stylegan2-ada-pytorch/train.py", line 531, in main
>     subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
>   File "/content/stylegan2-ada-pytorch/train.py", line 383, in subprocess_fn
>     training_loop.training_loop(rank=rank, **args)
>   File "/content/stylegan2-ada-pytorch/training/training_loop.py", line 375, in training_loop
>     dataset_kwargs=training_set_kwargs, num_gpus=num_gpus, rank=rank, device=device)
>   File "/content/stylegan2-ada-pytorch/metrics/metric_main.py", line 45, in calc_metric
>     results = _metric_dict[metric](opts)
>   File "/content/stylegan2-ada-pytorch/metrics/metric_main.py", line 85, in fid50k_full
>     fid = frechet_inception_distance.compute_fid(opts, max_real=None, num_gen=50000)
>   File "/content/stylegan2-ada-pytorch/metrics/frechet_inception_distance.py", line 27, in compute_fid
>     rel_lo=0, rel_hi=0, capture_mean_cov=True, max_items=max_real).get_mean_cov()
>   File "/content/stylegan2-ada-pytorch/metrics/metric_utils.py", line 215, in compute_feature_stats_for_dataset
>     for images, _labels in torch.utils.data.DataLoader(dataset=dataset, sampler=item_subset, batch_size=batch_size, **data_loader_kwargs):
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
>     data = self._next_data()
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1179, in _next_data
>     return self._process_data(data)
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
>     data.reraise()
>   File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 429, in reraise
>     raise self.exc_type(msg)
> AssertionError: Caught AssertionError in DataLoader worker process 1.
> Original Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/content/stylegan2-ada-pytorch/training/dataset.py", line 88, in __getitem__
>     assert list(image.shape) == self.image_shape
> AssertionError
> ```
> 
> That is however most likely an issue with the dataset. Tested this on a smaller chunk of the images and it started training.

**Comment by zimenglan-sysu-512** [comment]
hi @timendez 
did u solve it? can give some tips?

**Comment by timendez** [comment]
@zimenglan-sysu-512 no, sorry I never figured it out :(

**Comment by parkjh688** [comment]
I had same issue in another repo because I used multi workers. So I checked all the process with `ps -al` and kill every process.

**Comment by LukeLIN-web** [comment]
> I checked all the process with `ps -al` and kill every process.

great!  it worked.

**Comment by LukeLIN-web** [comment]
> > I checked all the process with `ps -al` and kill every process.
> 
> great! it worked.

really strange, now i cannot find any python process but it still fail.
