### ISSUE TITLE
Running StyleGAN on Arch Linux

### ISSUE THREAD

**Issue by jkraasch** [NVlabs/stylegan2-ada-pytorch#179]
I have been running the code just fine, but recently I cleaned my system and reinstalled cuda and all the packages. Since then I can't get the code running anymore. Every time ninja compiles the ops I receive the following error:

  File "/home/beans/Desktop/Autolume/vision/visualiser.py", line 4, in <module>
    from stylegan2.model import Generator
  File "/home/beans/Desktop/Autolume/stylegan2/model.py", line 11, in <module>
    from stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/beans/Desktop/Autolume/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/beans/Desktop/Autolume/stylegan2/op/fused_act.py", line 11, in <module>
    fused = load(
  File "/home/beans/Desktop/Autolume/venv/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1080, in load
    return _jit_compile(
  File "/home/beans/Desktop/Autolume/venv/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1293, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/beans/Desktop/Autolume/venv/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1405, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/beans/Desktop/Autolume/venv/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/2] /opt/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/beans/Desktop/Autolume/venv/lib/python3.9/site-packages/torch/include -isystem /home/beans/Desktop/Autolume/venv/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/beans/Desktop/Autolume/venv/lib/python3.9/site-packages/torch/include/TH -isystem /home/beans/Desktop/Autolume/venv/lib/python3.9/site-packages/torch/include/THC -isystem /opt/cuda/include -isystem /usr/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /home/beans/Desktop/Autolume/stylegan2/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o 
/opt/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/beans/Desktop/Autolume/venv/lib/python3.9/site-packages/torch/include -isystem /home/beans/Desktop/Autolume/venv/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/beans/Desktop/Autolume/venv/lib/python3.9/site-packages/torch/include/TH -isystem /home/beans/Desktop/Autolume/venv/lib/python3.9/site-packages/torch/include/THC -isystem /opt/cuda/include -isystem /usr/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /home/beans/Desktop/Autolume/stylegan2/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
/home/beans/Desktop/Autolume/venv/lib/python3.9/site-packages/torch/include/c10/core/TensorImpl.h(2179): error: static assertion failed with "You changed the size of TensorImpl on 64-bit arch.See Note [TensorImpl size constraints] on how to proceed."

1 error detected in the compilation of "/home/beans/Desktop/Autolume/stylegan2/op/fused_bias_act_kernel.cu".

I am using Cuda 11.4 and all the current ninja and torch packages.

I appreciate any help to get the code running on my system again!

**Comment by chi0tzp** [comment]
@jkraasch Any insight on this? Should just downgrading CUDA just work?

**Comment by chi0tzp** [comment]
@jkraasch In my case, using system-wide packages (`python-pytorch-cuda: 1.9.0-7`, `cuda: 11.4.2-1`, `cudnn: 8.2.4.15-1`), it works just fine. But I cannot figure out how to make it work inside a (python's native) virtual environment using pip. Any ideas?

**Comment by jkraasch** [comment]
I closed this issue because I realized I was in the wrong github tab, the NVlabs implementation works for me, but the rosinality one throws this error for me.
