### ISSUE TITLE
How can we use our own image dataset to generate a dataset with labeled format suitable for ADA training? (like cifar-10 for example)

### ISSUE THREAD

**Issue by ilem777** [NVlabs/stylegan2-ada-pytorch#18]
How can we use our own image dataset to generate a dataset with labeled format suitable for ADA training? (like cifar-10 for example)
I have separated my images with different name folders, and then used dataset_tool.py to generate ZIP dataset, but when I open the zip package, I found that all the images are still put into the one folder. Is there any way to use my own image dataset to generate a dataset with labels?
Thank you.

**Comment by nurpax** [comment]
Folders do not signify labels in our dataset format.  Instead, there's a file called `dataset.json` at the root of a dataset folder that contains labels.

I recommend constructing cifar-10 using the instrctions in the README.md and then inspecting this file.  When you construct your own dataset with labels, you should make a similar file that contains labels for your dataset elements.

Here's how the dataset.json structure looks like:

```
{
    "labels": [
        ["00000/img00000000.png",6],
        ["00000/img00000001.png",9],
        ... repeated for every image in the datase
        ["00049/img00049999.png",1]
    ]
}
```

Each element in the `labels` array is of form `[image_filename, label_index]`.

**Comment by ilem777** [comment]
@nurpax Thank you, very detailed explanation.

**Comment by nurpax** [comment]
NP!  I'll keep the bug open to remind me to expand on the labels part in the dataset_tool.py help and/or README.md.
