### ISSUE TITLE
Issue Calling Resume Training 

### ISSUE THREAD

**Issue by Passingbyposts** [NVlabs/stylegan2-ada-pytorch#183]
**Describe the bug**
Error Resuming training

**To Reproduce**
(stylegantry4) PS C:\Users\AA\temp\stylegan2-ada-pytorch> python train.py --data C:\Ganoutput --outdir C:\GanResults --resume=/C:/GanResults/00001-Ganoutput-auto1/network-snapshot-0800.pkl
>>
Training options:
{
  "num_gpus": 1,
  "image_snapshot_ticks": 50,
  "network_snapshot_ticks": 50,
  "metrics": [
    "fid50k_full"
  ],
  "random_seed": 0,
  "training_set_kwargs": {
    "class_name": "training.dataset.ImageFolderDataset",
    "path": "C:\\Ganoutput",
    "use_labels": false,
    "max_size": 13439,
    "xflip": false,
    "resolution": 512
  },
  "data_loader_kwargs": {
    "pin_memory": true,
    "num_workers": 3,
    "prefetch_factor": 2
  },
  "G_kwargs": {
    "class_name": "training.networks.Generator",
    "z_dim": 512,
    "w_dim": 512,
    "mapping_kwargs": {
      "num_layers": 2
    },
    "synthesis_kwargs": {
      "channel_base": 32768,
      "channel_max": 512,
      "num_fp16_res": 4,
      "conv_clamp": 256
    }
  },
  "D_kwargs": {
    "class_name": "training.networks.Discriminator",
    "block_kwargs": {},
    "mapping_kwargs": {},
    "epilogue_kwargs": {
      "mbstd_group_size": 4
    },
    "channel_base": 32768,
    "channel_max": 512,
    "num_fp16_res": 4,
    "conv_clamp": 256
  },
  "G_opt_kwargs": {
    "class_name": "torch.optim.Adam",
    "lr": 0.0025,
    "betas": [
      0,
      0.99
    ],
    "eps": 1e-08
  },
  "D_opt_kwargs": {
    "class_name": "torch.optim.Adam",
    "lr": 0.0025,
    "betas": [
      0,
      0.99
    ],
    "eps": 1e-08
  },
  "loss_kwargs": {
    "class_name": "training.loss.StyleGAN2Loss",
    "r1_gamma": 6.5536
  },
  "total_kimg": 25000,
  "batch_size": 8,
  "batch_gpu": 8,
  "ema_kimg": 2.5,
  "ema_rampup": null,
  "ada_target": 0.6,
  "augment_kwargs": {
    "class_name": "training.augment.AugmentPipe",
    "xflip": 1,
    "rotate90": 1,
    "xint": 1,
    "scale": 1,
    "rotate": 1,
    "aniso": 1,
    "xfrac": 1,
    "brightness": 1,
    "contrast": 1,
    "lumaflip": 1,
    "hue": 1,
    "saturation": 1
  },
  "resume_pkl": "/C:/GanResults/00001-Ganoutput-auto1/network-snapshot-0800.pkl",
  "ada_kimg": 100,
  "run_dir": "C:\\GanResults\\00004-Ganoutput-auto1-resumecustom"
}

Output directory:   C:\GanResults\00004-Ganoutput-auto1-resumecustom
Training data:      C:\Ganoutput
Training duration:  25000 kimg
Number of GPUs:     1
Number of images:   13439
Image resolution:   512
Conditional model:  False
Dataset x-flips:    False

Creating output directory...
Launching processes...
Loading training set...

Num images:  13439
Image shape: [3, 512, 512]
Label shape: [0]

Constructing networks...
Resuming from "/C:/GanResults/00001-Ganoutput-auto1/network-snapshot-0800.pkl"
Traceback (most recent call last):
  File "C:\Users\aa\temp\stylegan2-ada-pytorch\train.py", line 538, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "C:\Users\aa\.conda\envs\stylegantry4\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\aa\.conda\envs\stylegantry4\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\aa\.conda\envs\stylegantry4\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\aa\.conda\envs\stylegantry4\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\aa\.conda\envs\stylegantry4\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\aa\temp\stylegan2-ada-pytorch\train.py", line 531, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "C:\Users\aa\temp\stylegan2-ada-pytorch\train.py", line 383, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "C:\Users\aa\temp\stylegan2-ada-pytorch\training\training_loop.py", line 157, in training_loop
    with dnnlib.util.open_url(resume_pkl) as f:
  File "C:\Users\aa\temp\stylegan2-ada-pytorch\dnnlib\util.py", line 389, in open_url
    return url if return_filename else open(url, "rb")
OSError: [Errno 22] Invalid argument: '/C:/GanResults/00001-Ganoutput-auto1/network-snapshot-0800.pkl'

Please copy&paste text instead of screenshots for better searchability.

IM probably reading it wrong but the documentation is a little vague on how to call training resume 

--resume=~/training-runs/<NAME>/network-snapshot-<INT>.pkl resumes a previous training run.

Im assuming <NAME> isnt file path but is unclear as to what it is i should run 
Below is my file path but im not sure how to call its resumption 

python train.py --data C:\Ganoutput --outdir C:\GanResults --resume=/C:/GanResults/00001-Ganoutput-auto1/network-snapshot-0800.pkl

I assume im miscalling the resume function ???? 

![image](https://user-images.githubusercontent.com/37743982/134040638-48b75983-3739-48d0-9604-ee8cebc87c6c.png)

**Expected behavior**
Resuming Training

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PyTorch version (e.g., pytorch 1.7.1)
 - CUDA toolkit version (e.g., CUDA 11.0)
 - NVIDIA driver version
 - GPU RTX 3090
 - Docker: did you use Docker?  If yes, specify docker image URL (e.g., nvcr.io/nvidia/pytorch:20.12-py3)

**Additional context**

**Comment by trontronicent** [comment]
use regular windows path notation and enclose the path in quotation marks - had the same issues in the beginning.  On your posted RESUME path you have a leading / before the absolute path. If you start a path with a / it indicates a relative path, but i doubt on the current location there is a folder called "C:" ;)

Anyway, i personally prefer absolute paths (they never change on my calls, so i just use the full path enclosed in quotation marks ;)

Example of a working call 

python train.py --data="C:\DataSetPath.zip"" --cfg=stylegan256 --metrics=fid50k_full --snap=15 --imgsnap=5 --aug=noaug --seed=17777 --outdir="C:\ImageModelTrainingRuns" --resume="C:\ImageModelTrainingRuns\00039-Large256-paper256-batch64-ada-resumecustom\network-snapshot-000907.pkl" --batch=64

**Comment by Passingbyposts** [comment]
Thanks that worked perfectly, i was surprised with the tilde and thought it bizarre but as I'm new to it i just mindlessly accepted it :) 

Thanks alot
