### ISSUE TITLE
Dataset 1300 image, train to kimg has been 12k, then fake image view is changed color

### ISSUE THREAD

**Issue by thanhdatit** [NVlabs/stylegan2-ada-pytorch#205]
I have trained dataset 1300 image, train to kimg has been 12k, then fake image view is changed color, I don't know what's wrong?
do i have to adjust the gamma more ? because i leave everything as default

[https://anhsieuviet.com/image/LbN7qV](https://anhsieuviet.com/image/LbN7qV)

**Comment by Cantonaism** [comment]
Hi, D-Mad. I have same problem. Did you slove this problem? If you did it, please let me notice.

**Comment by D-Mad** [comment]
1k3 images seems a bit small, you use 3k datasets, I just fixed the above error like that

**Comment by Cantonaism** [comment]
Oh, I see. thankyou for your mention. I'll try with more datasets. Thankyou.
