### ISSUE TITLE
How does one get an intermediate output?

### ISSUE THREAD

**Issue by thoppe** [NVlabs/stylegan2-ada-pytorch#21]
I'm trying to generate intermediate outputs from a pre-trained model for a different downstream task. Since the network I'm feeding it to is 224x224 I only need to generate a 256x256 image, not the full 1024x1024. 

Digging through the code, it look like I could do something like this:

```python
with open('stylegan2-ada-pytorch_pretrained_metfaces.pkl', 'rb') as f:
    
    styleGAN2_ADA = pickle.load(f)
    G = styleGAN2_ADA['G_ema']
    G.synthesis.block_resolutions = [4, 8, 16, 32, 64, 128, 256,]
```

Which sort of works, but I think I'm missing the `is_final` flag on the last block. I'm not sure how to change it for a pre-trained model.

**Output when changing `.block_resolutions`**
![yHYBh](https://user-images.githubusercontent.com/2707106/106959421-a0329180-6708-11eb-826f-a33a79b31ea8.jpg)

**Standard output, same latent vector**
![NcQpT](https://user-images.githubusercontent.com/2707106/106959428-a163be80-6708-11eb-9605-79ae6049e57b.jpg)

**Comment by futscdav** [comment]
If the architecture is `skip` (default I believe), then the final output is the sum over all lower resolutions, so extracting an intermediate RGB without running the full network is not possible. However, it's pretty quick to finetune if you really would like to only run it up to the 256 resolution.

**Comment by woctezuma** [comment]
You could also pick a pre-trained network for the 256 resolution.

**Comment by thoppe** [comment]
Thanks @woctezuma that's a nice project to look over. 

I think I'll fine-tune the network directly for the 256 resolution as suggested @futscdav, it shouldn't be too hard!
