### ISSUE TITLE
Is it possible to run faster with DeepSpeed?

### ISSUE THREAD

**Issue by wodsoe** [NVlabs/stylegan2-ada-pytorch#23]
Is it possible to run faster with [DeepSpeed](https://github.com/microsoft/DeepSpeed)?

**Comment by Thierryonre** [comment]
I've been thinking about doing this with an unofficial version for AGES but I don't have the skills to implement it...
Since deepspeed does support GANs, I assume it would be possible.
I would love for someone to do this.
