### ISSUE TITLE
What's a tick?

### ISSUE THREAD

**Issue by George-Ogden** [NVlabs/stylegan2-ada-pytorch#242]
Sorry, probably a very simple question but what is a tick?

**Comment by PDillis** [comment]
A tick is a progress snapshot interval. By default, it's set that one tick equals 4 kimg or 4000 images that the Discriminator has seen. You could change this [here](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/6f160b3d22b8b178ebe533a50d4d5e63aedba21d/training/training_loop.py#L113), but it's not something that will affect the training itself of the model, only how often things are printed to the console and how many times the model and images are saved to disk.

**Comment by George-Ogden** [comment]
Thanks 👍
