### ISSUE TITLE
How to use the Discriminator

### ISSUE THREAD

**Issue by mulkong** [NVlabs/stylegan2-ada-pytorch#26]
Hi, I want to use Discriminator, but I am not sure what parameters are required. 
I would appreciate it if you let me know.

Thank you.

**Comment by mulkong** [comment]
I've tried this, but it doesn't work.

`D(x, None, aug='ada', target=0.7, p=0.0, augpipe='bgc')`

**Comment by B0RJA** [comment]
Explained in #168
