### ISSUE TITLE
some errors with windows10 with RTX-3070

### ISSUE THREAD

**Issue by SleepyPepperHead** [NVlabs/stylegan2-ada-pytorch#28]
**Describe the bug**
I'm new to this and I met these errors. I already installed required libraries and cleared the cache. 
I run the train.py with a customer dataset zip file and I keep get 'No module named 'upfirdn2d_plugin' warning.
But it seems still running since the memory of GPU is highly occupied.
Then comes 'Evaluating metrics...'   I then got this error:
'RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory'

**Screenshots**
![image](https://user-images.githubusercontent.com/60811549/107386165-8ccf5e00-6b2e-11eb-9d06-32a410420edf.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - PyTorch version (pytorch 1.7.1)
 - CUDA toolkit version (CUDA 11.0) [specifically it shows like this in pip list: 'torch 1.7.1+cu110']
 - NVIDIA driver version 8.1.940.0
 - GPU [ RTX 3070]
 - Docker: did you use Docker? no

**Here is my log**
[log.txt](https://github.com/NVlabs/stylegan2-ada-pytorch/files/5952314/log.txt)

**Comment by mjc619** [comment]
probably needs cuda 11.1 since the 3090 requires it, also you will probably not have enough vram to run as recommended.

**Comment by nurpax** [comment]
See if comments [here](https://github.com/NVlabs/stylegan2-ada-pytorch/issues/2#issuecomment-779457121) help.  Please re-open if this is something that's not covered in that bug.
