### ISSUE TITLE
cublas_v2.h: No such file or directory

### ISSUE THREAD

**Issue by NOlivier-Inria** [NVlabs/stylegan2-ada-pytorch#29]
**Describe the bug**
I am encountering a `cublas_v2.h: No such file or directory` error when using the command `python train.py --outdir=outdir --data=../fmwa256x256.zip --gpus=1`
Here's the more detailled error message :
```
Constructing networks...
Setting up PyTorch plugin "bias_act_plugin"... Failed!
/home/oliviern/stylegan2-ada-pytorch/torch_utils/ops/bias_act.py:50: UserWarning: Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:

Error building extension 'bias_act_plugin': [1/2] /home/oliviern/venv/singularity_pytorch/bin/x86_64-conda_cos6-linux-gnu-c++ -MMD -MF bias_act.o.d -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/TH -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/oliviern/venv/singularity_pytorch/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/oliviern/stylegan2-ada-pytorch/torch_utils/ops/bias_act.cpp -o bias_act.o 
FAILED: bias_act.o 
/home/oliviern/venv/singularity_pytorch/bin/x86_64-conda_cos6-linux-gnu-c++ -MMD -MF bias_act.o.d -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/TH -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/oliviern/venv/singularity_pytorch/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/oliviern/stylegan2-ada-pytorch/torch_utils/ops/bias_act.cpp -o bias_act.o 
In file included from /home/oliviern/stylegan2-ada-pytorch/torch_utils/ops/bias_act.cpp:10:0:
/home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:7:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

  warnings.warn('Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:\n\n' + str(sys.exc_info()[1]))
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!
/home//oliviern/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation.
```

**To Reproduce**
`python train.py --outdir=outdir --data=../fmwa256x256.zip --gpus=1`
I've also tried `CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/local/cuda/targets/x86_64-linux/include/ CUDA_HOME=/usr/local/cuda CUDA_PATH_V10_1=/usr/local/cuda/bin PYTHONPATH=/home/oliviern python train.py --outdir=outdir --data=../fmwa256x256.zip --gpus=1` which gives the same error

**Desktop (please complete the following information):**
 - Linux (CentOS 7, 3.10.0-862.3.2.el7.x86_64)
 - PyTorch 1.7.0
 - CUDA 10.2
 - Tesla V100 32GB
 - Running on a Singularity env

**Additional Information**
cublas_v2.h is present in `/usr/local/cuda/targets/x86_64-linux/include/`
```
ls /usr/local/cuda/targets/x86_64-linux/include/cublas*
/usr/local/cuda/targets/x86_64-linux/include/cublas_api.h  /usr/local/cuda/targets/x86_64-linux/include/cublas_v2.h
/usr/local/cuda/targets/x86_64-linux/include/cublas.h	   /usr/local/cuda/targets/x86_64-linux/include/cublasXt.h
```

What could be the issue ?

**Comment by Lover19** [comment]
No Interresse, Must Police 15.2.2021 

Nokia


Am 10.02.2021 um 06:41 schrieb NOlivier-Inria <notifications@github.com>:

﻿
Describe the bug
I am encountering a cublas_v2.h: No such file or directory error when using the command python train.py --outdir=outdir --data=../fmwa256x256.zip --gpus=1
Here's the more detailled error message :

Constructing networks...
Setting up PyTorch plugin "bias_act_plugin"... Failed!
/home/oliviern/stylegan2-ada-pytorch/torch_utils/ops/bias_act.py:50: UserWarning: Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:

Error building extension 'bias_act_plugin': [1/2] /home/oliviern/venv/singularity_pytorch/bin/x86_64-conda_cos6-linux-gnu-c++ -MMD -MF bias_act.o.d -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/TH -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/oliviern/venv/singularity_pytorch/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/oliviern/stylegan2-ada-pytorch/torch_utils/ops/bias_act.cpp -o bias_act.o 
FAILED: bias_act.o 
/home/oliviern/venv/singularity_pytorch/bin/x86_64-conda_cos6-linux-gnu-c++ -MMD -MF bias_act.o.d -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/TH -isystem /home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/oliviern/venv/singularity_pytorch/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/oliviern/stylegan2-ada-pytorch/torch_utils/ops/bias_act.cpp -o bias_act.o 
In file included from /home/oliviern/stylegan2-ada-pytorch/torch_utils/ops/bias_act.cpp:10:0:
/home/oliviern/venv/singularity_pytorch/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:7:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

  warnings.warn('Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:\n\n' + str(sys.exc_info()[1]))
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!
/home//oliviern/stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation.
To Reproduce
python train.py --outdir=outdir --data=../fmwa256x256.zip --gpus=1
I've also tried CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/local/cuda/targets/x86_64-linux/include/ CUDA_HOME=/usr/local/cuda CUDA_PATH_V10_1=/usr/local/cuda/bin PYTHONPATH=/home/oliviern python train.py --outdir=outdir --data=../fmwa256x256.zip --gpus=1 which gives the same error

Desktop (please complete the following information):

Linux (CentOS 7, 3.10.0-862.3.2.el7.x86_64)
PyTorch 1.7.0
CUDA 10.2
Tesla V100 32GB
Running on a Singularity env
Additional Information
cublas_v2.h is present in /usr/local/cuda/targets/x86_64-linux/include/

ls /usr/local/cuda/targets/x86_64-linux/include/cublas*
/usr/local/cuda/targets/x86_64-linux/include/cublas_api.h  /usr/local/cuda/targets/x86_64-linux/include/cublas_v2.h
/usr/local/cuda/targets/x86_64-linux/include/cublas.h	   /usr/local/cuda/targets/x86_64-linux/include/cublasXt.h
What could be the issue ?

**Comment by NOlivier-Inria** [comment]
It was in fact not related to stylegan2-ada-pytorch, but was due to a wrong include path

**Comment by Xjmengnieer** [comment]
hi，I have encountered the same problem. Have you solved this problem
