### ISSUE TITLE
Hints on RGBA image dataset

### ISSUE THREAD

**Issue by jeffshee** [NVlabs/stylegan2-ada-pytorch#33]
Hi. First of all, thanks for the release!

Currently, only grayscale and RGB image dataset are supported.
For example, ` dataset_tool.py` won't even allow RGBA images as input.
Could you give me some hints on the simplest modification to the source code for RGBA image to be considered and how feasible is it for stylegan2-ada to train on the RGBA image dataset?

Thanks!

**Comment by eps696** [comment]
check this 'remake' https://github.com/eps696/stylegan2ada
it has quite a few useful tweaks, including rgba support

**Comment by jeffshee** [comment]
@eps696 Hi, thanks for your work!
I will check that shortly to see if everything is work for me ^^
Close for now
