### ISSUE TITLE
No module named 'upfirdn2d_plugin'

### ISSUE THREAD

**Issue by lz1998** [NVlabs/stylegan2-ada-pytorch#35]
**Describe the bug**

```bash
No module named 'upfirdn2d_plugin'
  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n\n' + str(sys.exc_info()[1]))
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!
.../stylegan2-ada-pytorch/torch_utils/ops/upfirdn2d.py:34: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:
```

**To Reproduce**

```bash
python3 train.py --outdir=train_result --data=../data/dataset1.zip --gpus=8
```

Please copy&paste text instead of screenshots for better searchability.

**Desktop (please complete the following information):**

- CUDA 11.0
- Debian
- GPU V100
- torch python3 train.py --outdir=train_result --data=../data/dataset1.zip --gpus=8

**Additional context**

**Comment by gokhanbaydar** [comment]
I had the same problem, installed Windows 10 SDK and now its working fine.

**Comment by OvidiuSabau** [comment]
> I had the same problem, installed Windows 10 SDK and now its working fine.

What do you think the issue relates to? I'm encountering it too on Linux.

**Comment by nurpax** [comment]
Please see my comment https://github.com/NVlabs/stylegan2-ada-pytorch/issues/2#issuecomment-779457121

**Comment by OvidiuSabau** [comment]
Thanks a lot for the reply! My issue ended up being that the default gcc version was 7.3, which was incompatible with cuda. Installing gcc 5 through anaconda solved this for me. Just mentioning this in case someone else encounters this too.

**Comment by Karma1628** [comment]
> Thanks a lot for the reply! My issue ended up being that the default gcc version was 7.3, which was incompatible with cuda. Installing gcc 5 through anaconda solved this for me. Just mentioning this in case someone else encounters this too.

Thanks! very important! cuda version must consistent with gcc and g++ version

**Comment by mha142** [comment]
My gcc version is : 9.5.0 
I solved this issue by installing the following:

conda install ninja 

conda install cudatoolkit=11.1 -c conda-forge

pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
