### ISSUE TITLE
legacy.py conversion fails for some network pickles

### ISSUE THREAD

**Issue by derekphilipau** [NVlabs/stylegan2-ada-pytorch#36]
**Describe the bug**
Some Stylegan network pickles define "resolution_w" and "resolution_h" in addition to "resolution".  legacy.py only handles "resolution" and will fail with "Unknown TensorFlow kwarg"

**To Reproduce**
I have looked through the source of previous StyleGAN & StyleGAN2 releases and have not found which verson is defining "resolution_w" and "resolution_h" in addition to "resolution".

1. Download a legacy network pickle, for example [faces (FFHQ config-f 512x512) listed here](https://github.com/justinpinkney/awesome-pretrained-stylegan2#faces-FFHQ-config-f-512x512) or download from [Direct Link on Mega](https://mega.nz/#!eQdHkShY!8wyNKs343L7YUjwXlEg3cWjqK2g2EAIdYz5xbkPy3ng)
2. Run `python legacy.py --source=./ffhq-512-avg-tpurun1.pkl --dest=stylegan2-ada-ffh512-config-f.pkl`
3. This will fail with error "Unknown TensorFlow kwarg" due to "resolution_w" and "resolution_h" kwargs.  (In the example pkl, "resolution", "resolution_w" and "resolution_h" are all equal to 512.

**Expected behavior**
legacy.py should account for the existence of "resolution_w" and "resolution_h" kwargs.

**Fix**
In legacy.py lines 148 & 248 we check for unknown kwargs.

I'm not much of a python programmer, but in both of those sections adding this code will fix the issue:
```
    if 'resolution_w' in tf_kwargs:
        tf_kwargs.pop('resolution_w', None)
        tf_kwargs.pop('resolution_h', None)
```
This code should be inserted before lines 153 and 250:
```
unknown_kwargs = list(set(tf_kwargs.keys()) - known_kwargs)
```
Using this fix I have successfully converted the above linked FFHQ-config-f-512x512 network and run transfer learning against it.

**Desktop (please complete the following information):**
 - OS: Google Colab Pro, Python 3.6.9
 - PyTorch version 1.7.0+cu101
 - CUDA toolkit version release 10.1, V10.1.243
 - NVIDIA driver version NVIDIA UNIX x86_64 Kernel Module  460.32.03
 - GPU NVIDIA V100

**Comment by betterze** [comment]
This fix my error. Thx a lot.
