### ISSUE TITLE
How to download all files on "https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/" using one command?

### ISSUE THREAD

**Issue by PeterouZh** [NVlabs/stylegan2-ada-pytorch#4]
Hi,

I want to know how to download all the files provided on this website [https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/](https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/) using just one command. Can you help me?

Thanks!

**Comment by woctezuma** [comment]
You know it is at least 50 GB in total. If I were you, I would manually `wget` or `curl` the pre-trained networks here:
-   https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/
-   https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/transfer-learning-source-nets/
And leave the rest of the networks behind, especially the 40 GB of networks in the `paper` folders.

**Comment by nurpax** [comment]
Agree with what @woctezuma said.  Closing the bug.
