### ISSUE TITLE
Specify GPU in training options

### ISSUE THREAD

**Issue by Dhruva-Storz** [NVlabs/stylegan2-ada-pytorch#40]
Hi, I was wondering if there's any way to specify which GPU to train on. train.py only seems to have an option to specify the number of GPUs

I'm working on a shared system, so it would be awesome if we can selectively train on GPU 0, 1, or 2 only so it doesn't try to use a GPU that someone else is using or to train two models simultaneously.

**Comment by nurpax** [comment]
You should be able to use CUDA_VISIBLE_DEVICES environment variable on Linux (like `CUDA_VISIBLE_DEVICES=0`, `CUDA_VISIBLE_DEVICES=1` etc.) select which GPU the training process uses.

Or use Docker and the `--gpus` switch.
