### ISSUE TITLE
Error: Can not import "persistence" from torch_utils

### ISSUE THREAD

**Issue by ruanjiyang** [NVlabs/stylegan2-ada-pytorch#45]
Dear NVlabs

I face the issused :  Can not import "persistence" from torch_utils

as I checker, yes, there is no such module named persistence from torch_utils.  could you please check it again? thanks.

**Comment by ruanjiyang** [comment]
my mistake. I had found it. lets close the issues.

**Comment by GccX11** [comment]
I am facing the same issue, could you tell me where you found the dependency?

Thank you.

**Comment by y3h7rv** [comment]
well it seems to use torch_utils here(the torch_utils in this repo) to solve this [torch_utils](https://github.com/NVlabs/stylegan2-ada-pytorch/tree/main/torch_utils). download this torch_utils and put it in the root directory of your project. Not simply `pip install torch_utils `
