### ISSUE TITLE
Error: seeds required when generating from projected_w.npz

### ISSUE THREAD

**Issue by woctezuma** [NVlabs/stylegan2-ada-pytorch#5]
With the current code, one has to specify a dummy seed when generating images from `projected_w.npz`.

```bash
!python stylegan2-ada-pytorch/generate.py \
 --network={network_pkl} \
 --outdir={output_folder} \
 --projected-w={input_latent_vector}
```
is met with:
```bash
Usage: generate.py [OPTIONS]
Try 'generate.py --help' for help.

Error: Missing option '--seeds'.
```

However:
```bash
!python stylegan2-ada-pytorch/generate.py \
 --network={network_pkl} \
 --outdir={output_folder} \
 --seeds={dummy_seed} \
 --projected-w={input_latent_vector}
```
is met with:
```
Loading networks from "/content/lsundog-res256-paper256-kimg100000-noaug.pkl"...
warn: --seeds is ignored when using --projected-w
Generating images from projected W "out/1113080/projected_w.npz"
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
```

First, this is due to the code logic, and I am not sure whether it is intended.
https://github.com/NVlabs/stylegan2-ada-pytorch/blob/7bd6159279e558ccb14ecb0893e79e31d2f3be31/generate.py#L88-L100
followed by:
https://github.com/NVlabs/stylegan2-ada-pytorch/blob/7bd6159279e558ccb14ecb0893e79e31d2f3be31/generate.py#L102-L103

Second, the "fail" message is not shown. Only the "warn" message and the "missing argument" message are shown.

**Comment by nurpax** [comment]
My bad.. definitely not intended.  I must've had an extra "--seeds" arg on my command line when I was testing it.  I'll fix for the next update.

**Comment by portvs** [comment]
Error: Missing option '--network'
https://github.com/NVlabs/stylegan3
