### ISSUE TITLE
Error building extension 'upfirdn2d_plugin' and 'bias_act_plugin'

### ISSUE THREAD

**Issue by KhoaVo** [NVlabs/stylegan2-ada-pytorch#67]
I have a similar bug to this issue
#https://github.com/NVlabs/stylegan2-ada-pytorch/issues/39

However I think it's a bit different.
I get similar errors for both upfirdn2d_plugin and  bias_act_plugin

Here's the stack
Traceback (most recent call last):
  File "train.py", line 538, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 531, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 383, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "Y:\projects\stylegan2ada\training\training_loop.py", line 166, in training_loop
    img = misc.print_module_summary(G, [z, c])
  File "Y:\projects\stylegan2ada\torch_utils\misc.py", line 212, in print_module_summary
    outputs = module(*inputs)
  File "C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "Y:\projects\stylegan2ada\training\networks.py", line 499, in forward
    img = self.synthesis(ws, **synthesis_kwargs)
  File "C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "Y:\projects\stylegan2ada\training\networks.py", line 471, in forward
    x, img = block(x, img, cur_ws, **block_kwargs)
  File "C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "Y:\projects\stylegan2ada\training\networks.py", line 405, in forward
    x = self.conv0(x, next(w_iter), fused_modconv=fused_modconv, **layer_kwargs)
  File "C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "Y:\projects\stylegan2ada\training\networks.py", line 300, in forward
    padding=self.padding, resample_filter=self.resample_filter, flip_weight=flip_weight, fused_modconv=fused_modconv)
  File "Y:\projects\stylegan2ada\torch_utils\misc.py", line 101, in decorator
    return fn(*args, **kwargs)
  File "Y:\projects\stylegan2ada\training\networks.py", line 65, in modulated_conv2d
    x = conv2d_resample.conv2d_resample(x=x, w=weight.to(x.dtype), f=resample_filter, up=up, down=down, padding=padding, flip_weight=flip_weight)
  File "Y:\projects\stylegan2ada\torch_utils\misc.py", line 101, in decorator
    return fn(*args, **kwargs)
  File "Y:\projects\stylegan2ada\torch_utils\ops\conv2d_resample.py", line 139, in conv2d_resample
    x = upfirdn2d.upfirdn2d(x=x, f=f, padding=[px0+pxt,px1+pxt,py0+pyt,py1+pyt], gain=up**2, flip_filter=flip_filter)
  File "Y:\projects\stylegan2ada\torch_utils\ops\upfirdn2d.py", line 160, in upfirdn2d
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "Y:\projects\stylegan2ada\torch_utils\ops\upfirdn2d.py", line 31, in _init
    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "Y:\projects\stylegan2ada\torch_utils\custom_ops.py", line 110, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)
  File "C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\utils\cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\utils\cpp_extension.py", line 1302, in _jit_compile
    is_standalone=is_standalone)
  File "C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\utils\cpp_extension.py", line 1407, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\utils\cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'upfirdn2d_plugin': ninja: error: build.ninja:3: lexing error

It's saying something about a lexing error when ninja is trying to build

My nvcc --version returns

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:12:04_Pacific_Daylight_Time_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.relgpu_drvr455TC455_06.29069683_0

**Comment by nurpax** [comment]
The stacktrace is a little hard to read as it seems to have lost linefeeds somehow?

But the last error message seems to be pointing to a somehow corrupted build.ninja file.  This is what pytorch generates when building C++ extensions.

Please check the contents of the generated `build.ninja` file and copy&paste its contents here.  

I don't remember where exactly it resides on Windows.  On Linux it's at ~/.cache/torch_extensions.  Please refer to https://pytorch.org/docs/stable/cpp_extension.html, and look for `TORCH_EXTENSIONS_DIR`.

**Comment by KhoaVo** [comment]
Here's the output for bias_act_plugin build.ninja

```
ninja_required_version = 1.3
cxx = cl
nvcc = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\nvcc.exe

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc

cflags = -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\include -IC:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\include\TH -IC:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\nvcc.exe

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include" -IC:\Users\vokho\anaconda3\envs\stylegan\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc
post_cflags = 
cuda_cflags = -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\include -IC:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\include\TH -IC:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\nvcc.exe

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include" -IC:\Users\vokho\anaconda3\envs\stylegan\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --use_fast_math
cuda_post_cflags = 
ldflags = /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda_cu.lib -INCLUDE:?searchsorted_cuda@native@at@@YA?AVTensor@2@AEBV32@0_N1@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\Users\vokho\anaconda3\envs\stylegan\lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\Users\vokho\anaconda3\envs\stylegan\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\nvcc.exe

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\lib/x64" cudart.lib

rule compile
  command = cl /showIncludes $cflags -c $in /Fo$out $post_cflags
  deps = msvc

rule cuda_compile
  depfile = $out.d
  deps = gcc
  command = $nvcc --generate-dependencies-with-compile --dependency-output $out.d $cuda_cflags -c $in -o $out $cuda_post_cflags

rule link
  command = "C$:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64/link.exe" $in /nologo $ldflags /out:$out

build bias_act.o: compile Y$:\projects\stylegan2ada\torch_utils\ops\bias_act.cpp
build bias_act.cuda.o: cuda_compile Y$:\projects\stylegan2ada\torch_utils\ops\bias_act.cu

build bias_act_plugin.pyd: link bias_act.o bias_act.cuda.o

default bias_act_plugin.pyd
```

**Comment by nurpax** [comment]
Couple of things you could try to debug further:

1. Run `ninja` (without any arguments) in the same directory where you found the `build.ninja` file.  This should allow you to locally debug what's wrong with the build.  If you want to get this working, just iteratively try to debug why the ninja build could be going wrong.
2. If you don't succeed, also worth trying is removing the whole torch extensions directory and running stylegan2-ada-pytorch again and see if that helps.  (This is just in case some of the files in the extensions build temp dir is corrupted somehow.)

A quick look at your above output, it looks like somehow the `build.ninja` file gets generated wrong.  Why are these 3 lines of nvcc.exes after the `nvcc = ...` line? 

Maybe you have multiple CUDA toolkits in PATH?  Or maybe something wrong with your CUDA_HOME variable?

My guess is that your environment is incompatible with how torch extension build expects it to be in order to build stylegan2-ada pytorch extensions.  Many people have reported problems with custom extension building and almost always the problem has been some sort of an inconsistent CUDA toolkit installation.  I'd recommend you try to remove the extra CUDA toolkits from your path, re-run, and look at the generated `build.ninja` file, rebuilding until you succeed.

For reference, here's how the `build.ninja` file looks on my computer:

```
ninja_required_version = 1.3
cxx = c++
nvcc = /usr/local/cuda/bin/nvcc

cflags = -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/janne/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14
post_cflags = 
cuda_cflags = -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/janne/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' --use_fast_math -std=c++14
cuda_post_cflags = 
ldflags = -shared -L/home/janne/anaconda3/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart

rule compile
  command = $cxx -MMD -MF $out.d $cflags -c $in -o $out $post_cflags
  depfile = $out.d
  deps = gcc

rule cuda_compile
  command = $nvcc $cuda_cflags -c $in -o $out $cuda_post_cflags

rule link
  command = $cxx $in $ldflags -o $out

build bias_act.o: compile /home/janne/dev/cudagl/src/torch_utils/ops/bias_act.cpp
build bias_act.cuda.o: cuda_compile /home/janne/dev/cudagl/src/torch_utils/ops/bias_act.cu

build bias_act_plugin.so: link bias_act.o bias_act.cuda.o

default bias_act_plugin.so
```

**Comment by KhoaVo** [comment]
Thanks for the tips. I learned a lot about ninja today.
I ended up cleaning out all other CUDA installs except 11.2 and it seems to be working now.

**Comment by FangliangBai** [comment]
Hi everyone, here I share my issue and fix when encountering the 'upfirdn2d_plugin' and 'bias_act_plugin' problem.

The terminal output basically said the programme couldn't find `nvcc` and `cuda_runtime_api.h` and something like that.

Inspired by @nurpax 's answer, I checked the `build.ninja` file under `~/.cache/torch_extensions/bias_act_plugin/`. It shows:
```
ninja_required_version = 1.3
cxx = c++
nvcc = /usr/local/cuda:/bin/nvcc
```
Obviously, the nvcc path is wrong. So I check it In my `~/.zshrc`: `export CUDA_HOME=/usr/local/cuda:$CUDA_HOME`. OK, that is the problem, so I changed it to `export CUDA_HOME=/usr/local/cuda`.

The nvcc path of `build.ninja` afterwords became `nvcc = /usr/local/cuda/bin/nvcc` and it fixed the issue. Compling passed.

Finally, my env is 
Ubuntu 16.04
shell: zsh
gcc: gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
Pytorch : 1.7.1+cu110
CUDA : 11.0.3

**Comment by trontronicent** [comment]
@KhoaVo : Cleaning other Cudas is usually not required, as long as the first resolved Cuda Paths from the environment variables are the right version. So just clearing the others from the path environment variable usually is enough, but yeah - things can get messy sometimes especially with Stylegan and its specific version requirements that change.
I remember trying to get Stylegan1 to work under Windows , took me days (no python, conda etc. knowledge before)

**Comment by mhgenerate** [comment]
> Couple of things you could try to debug further:
> 
> 1. Run `ninja` (without any arguments) in the same directory where you found the `build.ninja` file.  This should allow you to locally debug what's wrong with the build.  If you want to get this working, just iteratively try to debug why the ninja build could be going wrong.
> 2. If you don't succeed, also worth trying is removing the whole torch extensions directory and running stylegan2-ada-pytorch again and see if that helps.  (This is just in case some of the files in the extensions build temp dir is corrupted somehow.)
> 
> A quick look at your above output, it looks like somehow the `build.ninja` file gets generated wrong. Why are these 3 lines of nvcc.exes after the `nvcc = ...` line?
> 
> Maybe you have multiple CUDA toolkits in PATH? Or maybe something wrong with your CUDA_HOME variable?
> 
> My guess is that your environment is incompatible with how torch extension build expects it to be in order to build stylegan2-ada pytorch extensions. Many people have reported problems with custom extension building and almost always the problem has been some sort of an inconsistent CUDA toolkit installation. I'd recommend you try to remove the extra CUDA toolkits from your path, re-run, and look at the generated `build.ninja` file, rebuilding until you succeed.
> 
> For reference, here's how the `build.ninja` file looks on my computer:
> 
> ```
> ninja_required_version = 1.3
> cxx = c++
> nvcc = /usr/local/cuda/bin/nvcc
> 
> cflags = -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/janne/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14
> post_cflags = 
> cuda_cflags = -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/janne/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/janne/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' --use_fast_math -std=c++14
> cuda_post_cflags = 
> ldflags = -shared -L/home/janne/anaconda3/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart
> 
> rule compile
>   command = $cxx -MMD -MF $out.d $cflags -c $in -o $out $post_cflags
>   depfile = $out.d
>   deps = gcc
> 
> rule cuda_compile
>   command = $nvcc $cuda_cflags -c $in -o $out $cuda_post_cflags
> 
> rule link
>   command = $cxx $in $ldflags -o $out
> 
> build bias_act.o: compile /home/janne/dev/cudagl/src/torch_utils/ops/bias_act.cpp
> build bias_act.cuda.o: cuda_compile /home/janne/dev/cudagl/src/torch_utils/ops/bias_act.cu
> 
> build bias_act_plugin.so: link bias_act.o bias_act.cuda.o
> 
> default bias_act_plugin.so
> ```

Thank you! It seems like the issue I was having was that I had 2 cuda toolkit paths (11.2,11.8) removing 11.8 worked perfectly for me. Thank you so much!
