### ISSUE TITLE
Can I continue training a pkl started in tensorflow stylegan2-ada in stylegan2-ada-pytorch?

### ISSUE THREAD

**Issue by MoemaMike** [NVlabs/stylegan2-ada-pytorch#74]
Can I continue training a pkl started in tensorflow stylegan2-ada in stylegan2-ada-pytorch?

I am working in Colab. Ran into an issue with  stylegan2-ada-pytorch so i fell back to  stylegan2-ada tensorflow. Have trained that model for a few days but  if the pytorch issue is resolved can i resume training that pkl with stylegan2-ada-pytorch?

**Comment by nurpax** [comment]
The pytorch version should be able to load many pkls created with the TensorFlow version.  This is mentioned in the README: "Compatible with old network pickles created using the TensorFlow version.".

**Comment by MoemaMike** [comment]
awesome
