### ISSUE TITLE
GPU Memory extensive usage

### ISSUE THREAD

**Issue by dokluch** [NVlabs/stylegan2-ada-pytorch#80]
**Describe the bug**
I am training on a RTX A6000 with `--cfg stylegan2` and getting almost 40 gigs of VRAM occupied permanently, even though the log shows that each step needs no more than 3 gigabytes. It's only 0th tick that takes this much memory.
Clearing torch cache does not help. 
Is there any way around this?

**To Reproduce**
1. Run train.py with `--cfg stylegan2` (`--cfg auto `does not consume this much memory)

**Expected behavior**
Release unused memory. 

**Screenshots**

<img width="1152" alt="Screenshot 2021-03-27 at 13 06 39" src="https://user-images.githubusercontent.com/135181/112717530-77579d00-8efe-11eb-9dc2-56a506067aa9.png">
<img width="581" alt="Screenshot 2021-03-27 at 13 07 11" src="https://user-images.githubusercontent.com/135181/112717533-7b83ba80-8efe-11eb-96c1-3cc08537759d.png">

**Desktop:**
 - OS: Windows 10
 - PyTorch version  1.7.1
 - CUDA toolkit version 11.2
 - NVIDIA driver version 461.72
 - GPU RTX A6000
 - Docker: no

**Comment by nurpax** [comment]
The first step runs internal cuDNN benchmarking in PyTorch.  This uses a lot of memory but should be harmless.  You can try adding `--nobench=1`  to disable this.

Does this cause problems for you or is this just an observation that a lot of memory is used at the start of training?

**Comment by dokluch** [comment]
> The first step runs internal cuDNN benchmarking in PyTorch. This uses a lot of memory but should be harmless. You can try adding `--nobench=1` to disable this.
> 
> Does this cause problems for you or is this just an observation that a lot of memory is used at the start of training?

Would disable benchmarking affect performance?
And yes, it does cause minor troubles when inferring other networks in parallel or doing some light GPU related tasks while stylegan is training. I've had out of memory issues a couple of times when saving network snapshot.

**Comment by nurpax** [comment]
It does affect performance somewhat.  You should benchmark to find out by how much.  I'd imagine it's in the range of 5-15%.

I'm not sure how, but maybe there is a way to limit the GPU memory usage per process on Windows.  You could set some sort of an upperlimit in which case I imagine the pytorch/cudnn benchmarking pass will not allocate more than what you allow it.

I'm closing this bug as it's more of a pytorch & cudnn issue than something specific to stylegan2-ada.
