### ISSUE TITLE
About Image Synthesis with Custom Noise Input

### ISSUE THREAD

**Issue by sailor002** [NVlabs/stylegan2-ada-pytorch#90]
Hi, thanks for the great work. I would like to ask if it's possible to use a custom noise to synthesize the image. My objective is about noise optimization, so I need to be able to feed a custom pre-determined noise into the network other than the "none", "random", and "const" options. I tried manipulating the network code, but since it's loaded from the pickle, I'm not able to make any changes. So either a custom noise option or a way to edit network code would be enough. Thanks...

**Comment by nurpax** [comment]
You can.  This is done in [projector.py](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/projector.py), you will find everything you need there.  You don't need to change the network code.

**Comment by sailor002** [comment]
Thanks. I'll check it out.
